### PR TITLE
TS - Adding toBeVisible declaration

### PR DESCRIPTION
**Pull request by smacpherson64**
**What**:

Adding toBeVisible to typescript definitions

**Why**:

To help typescript to know about the toBeVisible matcher

**How**:

I added the toBeVisible declaration as part of the interface

**Checklist**:

* [x] Documentation N\A
* [x] Tests N\A
* [x] Ready to be merged
* [x] Added myself to contributors table N/A

### CODE REVIEW

**Comment by smacpherson64** [comment]
Hi there @gnapse or @kentcdodds, just checking in about the PR to add the TS type for toBeVisible in jest-dom. Let me know if there is anything you would like changed.

Thank you for your time!

**Comment by kentcdodds** [comment]
Thank you for your patience. Sorry that it took so long to merge!

**Comment by smacpherson64** [comment]
Seriously, no worries, thank you for responding and your time! Glad to be able to help!

**Pull request merged**
