### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by r-walsh**
**What**:

`toBeThruthy` -> `toBeTruthy`

**Why**:

**How**:

I started by backspacing the extra `h`. Then I opened this PR.

**Checklist**:

* [x] Documentation
* [ ] Tests N/A
* [ ] Updated Type Definitions N/A
* [x] Ready to be merged 
* [ ] Added myself to contributors table N/A

### CODE REVIEW

**Comment by smacpherson64** [comment]
Hahaha! Great gif! 😂

**Comment by smacpherson64** [comment]
Thank you @r-walsh!

**Comment by kentcdodds** [comment]
> I wonder if it would be possible to run tests on a README's code examples? 🤔 :mind_blown: 😆

I'm pretty sure there are modules for this... Someone tried to convince me to use it but it seemed like too much work...

**Comment by gnapse** [comment]
Of course there are modules for that (or anything). This is javascript after all 😆.

But no, really, I'm (a bit) surprised anyway.

And yeah, agree it may be too much.

**Pull request merged**
